baseURL = 'https://wilonweb.github.io/hugo-blank-theme/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'sandbox'

paginate = 2


[[menu.main]]
  name = "A propos"
  url = "/a-propos"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[[menu.main]]
  name = "categories"
  url = "/categories"  
  
[[menu.main]]
  name = "genres"
  url = "/genres"  
 
  
[[menu.main]]
    name = "Contact"
    url = "/contact"  
  
[[menu.social]]
name = "GitHub"
url = "https://github.com/VotreCompteGithub"
pre = "<i class='fab fa-github'></i>"

[[menu.social]]
name = "Twitter"
url = "https://twitter.com/VotreCompteTwitter"
pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
name = "A propos"
url = "/a-propos"

[[menu.footer]]
name = "Protection des données"
url = "/protection-des-donnees"


[params]
    author = "Alex"
    authorImage = "/images/avatar-musk.jpg"
    mainSections = ["tutos","blog"]


# Déclaration des taxonomie
[taxonomies]
  category = 'categories'
  tag = 'tags'
  genre = 'genres'

# fonction de mise en relation
[related]
    threshold = 80 
    includeNewer = true
    toLower = true

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10

# Ajout du unsafe mode dans config.toml pour ajouter du html dans le markdown
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
            


